CC=g++

CFLAGS_DEBUG=-Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_EJUDGE_CLIENT_SIDE




all: $(OBJECTS)

OBJECTS/%.o : %.c
	$(CC) -c $(CFLAGS) $< -o $@

addprefix

SOURCES = main.c fileReading.c wstrcmp.c outputText.c wqsort.c structCmp.c objectSwapper.c

main.exe: $(OBJECTS)
	$(CC)  $(OBJECTS) -o main.exe

run: main.exe
	main.exe
clean:
	rm *.o*.exe
